version: 2

sources:
  - name: chesscom
    schema: public
    tables:
      - name: division_stats
        columns:
          - name: id
            description: Primary artificial key
          - name: ts
            description: timestamp when the data was gathered
          - name: division
            description: division id
          - name: username
            description: chess.com username
          - name: ranking
            description: Rank in the division at the timestamp given
          - name: trophy
            description: Number of trophy points
      - name: division
        columns:
          - name: id
            description: chess.com id of the division
          - name: description
            description: Name of the division
          - name: players
            description: array of players of interest participating in the division
          - name: is_active
            description: flag whether a given division is currently actively monitored
      - name: games
        columns:
          - name: id
            description: chess.com id of the game
          - name: username
            description: chess.com username for which this game was retrieved
          - name: division
            description: division id where the game was played (based on timestamp of the game)
          - name: white_username
            description: username of the player playing the white pieces
          - name: white_rating
            description: rating of the player playing the white pieces
          - name: white_result
            description: end game result for the player playing the white pieces
          - name: black_username
            description: username of the player playing the black pieces
          - name: black_rating
            description: rating of the player playing the black pieces
          - name: black_result
            description: end game result for the player playing the black pieces
          - name: url
            description: url to the view of the game on chess.com
          - name: time_control
            description: time control for the game, in seconds, with possible move increments
          - name: time_class
            description: time class for the game
          - name: rules
            description: chess rules applied in the game
          - name: end_time
            description: timestamp when the game ended
          - name: opening
            description: chess.com name of the opening
          - name: opening_code
            description: standard opening code
